// Generated by gencpp from file beginner_tutorials/Timer.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TIMER_H
#define BEGINNER_TUTORIALS_MESSAGE_TIMER_H

#include <ros/service_traits.h>


#include <beginner_tutorials/TimerRequest.h>
#include <beginner_tutorials/TimerResponse.h>


namespace beginner_tutorials
{

struct Timer
{

typedef TimerRequest Request;
typedef TimerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Timer
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Timer > {
  static const char* value()
  {
    return "472e4839166f9f2327e4f05d74c70af9";
  }

  static const char* value(const ::beginner_tutorials::Timer&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Timer > {
  static const char* value()
  {
    return "beginner_tutorials/Timer";
  }

  static const char* value(const ::beginner_tutorials::Timer&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::TimerRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::Timer >
template<>
struct MD5Sum< ::beginner_tutorials::TimerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Timer >::value();
  }
  static const char* value(const ::beginner_tutorials::TimerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::TimerRequest> should match
// service_traits::DataType< ::beginner_tutorials::Timer >
template<>
struct DataType< ::beginner_tutorials::TimerRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Timer >::value();
  }
  static const char* value(const ::beginner_tutorials::TimerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::TimerResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::Timer >
template<>
struct MD5Sum< ::beginner_tutorials::TimerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Timer >::value();
  }
  static const char* value(const ::beginner_tutorials::TimerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::TimerResponse> should match
// service_traits::DataType< ::beginner_tutorials::Timer >
template<>
struct DataType< ::beginner_tutorials::TimerResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Timer >::value();
  }
  static const char* value(const ::beginner_tutorials::TimerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TIMER_H
