// Generated by gencpp from file beginner_tutorials/TimerRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TIMERREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_TIMERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct TimerRequest_
{
  typedef TimerRequest_<ContainerAllocator> Type;

  TimerRequest_()
    : printing(false)  {
    }
  TimerRequest_(const ContainerAllocator& _alloc)
    : printing(false)  {
  (void)_alloc;
    }



   typedef uint8_t _printing_type;
  _printing_type printing;





  typedef boost::shared_ptr< ::beginner_tutorials::TimerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::TimerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TimerRequest_

typedef ::beginner_tutorials::TimerRequest_<std::allocator<void> > TimerRequest;

typedef boost::shared_ptr< ::beginner_tutorials::TimerRequest > TimerRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::TimerRequest const> TimerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::TimerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::TimerRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::TimerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.printing == rhs.printing;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::TimerRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::TimerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::TimerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::TimerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::TimerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "424d19f59af93153953d3ef5c3614349";
  }

  static const char* value(const ::beginner_tutorials::TimerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x424d19f59af93153ULL;
  static const uint64_t static_value2 = 0x953d3ef5c3614349ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/TimerRequest";
  }

  static const char* value(const ::beginner_tutorials::TimerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool printing\n"
;
  }

  static const char* value(const ::beginner_tutorials::TimerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.printing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::TimerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::TimerRequest_<ContainerAllocator>& v)
  {
    s << indent << "printing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.printing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TIMERREQUEST_H
